[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/v1/*"
  to = "/.netlify/functions/v1/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/v1/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  NODE_ENV = "production" 